parameters:
#    phnx_vcc.example.class: phnx\VccBundle\Example

services:
#    phnx_vcc.example:
#        class: %phnx_vcc.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
