phnxStatsBundle:
    resource: "@phnxStatsBundle/Controller/"
    type:     annotation
    prefix:   /

phnxTrainingPlannerBundle:
    resource: "@phnxTrainingPlannerBundle/Controller/"
    type:     annotation
    prefix:   /

phnxVccBundle:
    resource: "@phnxVccBundle/Resources/config/routing.yml"
    prefix:   /


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
