security:
    encoders:
        phnx\VccBundle\Entity\User: plaintext
        #Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_CLUB_ADMIN:  ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: phnxVccBundle:User, property: emailaddress }
            #users:
            #    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
            #    club:  { password: userpass, roles: [ 'ROLE_CLUB_ADMIN' ] }
            #    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        
            

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        login:
            pattern:  ^/login$
            security: false

        secured:
            pattern:    ^/
            anonymous:  true
            security:   true
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/club*, roles:ROLE_USER}
        - { path: ^/user*, roles:ROLE_USER}        
        - { path: ^/, roles:IS_AUTHENTICATED_ANONYMOUSLY}
